FROM continuumio/miniconda3

ARG user=codatalab
ARG homedir=/home

RUN apt-get update -qq \
    && apt-get install -yqq --no-install-recommends wget gzip \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/* \
    \
    && useradd --create-home --shell /bin/bash --uid 2001  ${user} \
    && chown -R ${user}:${user} ${homedir}/${user}
    

WORKDIR ${homedir}/${user}
USER ${user}

COPY --chown=${user} init-resources/entrypoint /entrypoint
ENTRYPOINT [ "/entrypoint" ]
