#!/bin/bash

printf "\n\033[0;44m---> Starting the gunicorn server.\033[0m\n"

eval "$(conda shell.bash hook)"
conda activate capfalcnlp
gunicorn --config ~/gunicorn.conf.py toolbox:app


printf "\n\033[0;44m---> Starting the SSH server.\033[0m\n"

/usr/sbin/sshd -D -f /opt/ssh/sshd_config

exec "$@"
