#!/bin/bash

printf "\n\033[0;44m---> Starting the gunicorn server.\033[0m\n"

eval "$(conda shell.bash hook)"
conda activate capfalcnlp

cd ~/capfalcnlp
pip install -r requirements.txt
pip install -e .

python -c "from capfalcnlp.helpers import load_model; load_model()"

gunicorn --config /usr/local/etc/gunicorn.conf.py toolbox:app


printf "\n\033[0;44m---> First request to load the models.\033[0m\n"
python ~/capfalcnlp/cli.py --input-file ~/capfalcnlp/example_text.txt


printf "\n\033[0;44m---> Starting the SSH server.\033[0m\n"

/usr/sbin/sshd -D -f /opt/ssh/sshd_config

exec "$@"
