#!/bin/bash

printf "\n\033[0;44m---> Downloading models...\033[0m\n"

if [[ $(ls ~/capfalcnlp/resources/models/fasttext-vectors | wc -l) != 2 ]]; then
    mkdir -p ~/capfalcnlp/resources/models/fasttext-vectors/
    cd "$_" || return
    wget -q https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.fr.300.vec.gz
    gzip -d cc.fr.300.vec.gz
    wget -q https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.en.300.vec.gz
    gzip -d cc.en.300.vec.gz
    cd ~/capfalcnlp || return
    pip install --no-cache-dir 'spacy<3'
    python -m spacy download en_core_web_md
    python -m spacy download fr_core_news_md
fi
